version: '3.8'

services:
  salvapos-backend:
    image: salvapos-backend:1.0-SNAPSHOT
    container_name: salvapos-backend
    environment:
      - DATABASE_HOST=salvaserver.mysql.database.azure.com
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=posadmin
      - DATABASE_PASSWORD=Capstone24
      - DATABASE_NAME=salvabase
    ports:
      - "3000:3000"
    networks:
      - salvapos_network

networks:
  salvapos_network:
    driver: bridge
