apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:533315175931:certificate/814c3cdb-2c18-439a-ae0f-7c76f7b43b81
    # Only run TLS on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    io.kompose.service: salvapos-backend
  name: salvapos-backend
spec:
  ports:
    - name: https
      port: 443
      targetPort: 3000  
  type: LoadBalancer
  selector:
    io.kompose.service: salvapos-backend
