apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: salvapos-backend
  name: salvapos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: salvapos-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: salvapos-backend
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: salvaserver.mysql.database.azure.com
            - name: DATABASE_NAME
              value: salvabase
            - name: DATABASE_PASSWORD
              value: Capstone24
            - name: DATABASE_PORT
              value: '3306'
            - name: DATABASE_USERNAME
              value: posadmin

            - name: FILE_URL
              value: https://salvapos-api.3itapp.com
            - name: URL_FRONTEND
              value: https://salvapos-front.3itapp.com
            - name: TZ
              value: America/Santiago

          image: 533315175931.dkr.ecr.us-east-1.amazonaws.com/salvapos-backend:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: salvapos-backend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
